plugins:
  - rubocop-capybara
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rails

AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRailsVersion: 8.0
  Exclude:
    - 'bin/**'
    - 'db/migrate/**'
    - 'db/schema.rb'
    - 'vendor/bundle/**/*'
    - 'vendor/**/*'
    - 'node_modules/**'
    - 'tmp/**'
    - 'coverage/**'

Layout/LineLength:
  Exclude:
    - 'config/initializers/devise.rb'

Metrics/BlockLength:
  Exclude:
    - 'config/environments/*'
    - 'config/routes.rb'

Rails/SkipsModelValidations:
  Exclude:
    - 'app/services/analytics/view_increment.rb'
