plugins:
  - rubocop-capybara
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rails

AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRailsVersion: 8.0
  Exclude:
    - 'bin/**'
    - 'db/migrate/**'
    - 'db/schema.rb'
    - 'db/cache_schema.rb'

Layout/LineLength:
  Exclude:
    - 'config/initializers/devise.rb'

Metrics/BlockLength:
  Exclude:
    - 'config/environments/*'
    - 'config/routes.rb'
