development:
  adapter: mysql2
  database: tanooki_development
  host: localhost
  username: root
  password: mypassword
  socket: /var/run/mysqld/mysqld.sock

test:
  adapter: mysql2
  database: tanooki_test
  host: localhost
  username: root
  password: mypassword
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql2
  database: <%= ENV['DB_NAME'] %>
  host: <%= ENV['DB_HOST'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
