development:
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4_general_ci
  collation: utf8mb4_general_ci
  database: tanooki_development
  host: localhost
  username: root
  password: mypassword

test:
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4_general_ci
  collation: utf8mb4_general_ci
  database: tanooki_test
  host: 127.0.0.1
  username: root
  password: mypassword
  collation: utf8mb4_general_ci

production:
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4_general_ci
  collation: utf8mb4_general_ci
  database: tanooki_production
  host: ls-67015b39face583a25fd2c4f7ebcfae0daeb3738.cor3k60vx5qc.eu-central-1.rds.amazonaws.com
  username: ubuntu
  password: N7BgK,v9|gK#Vv+^nlBYw3W8pQe51-ZD
