development:
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4_general_ci
  collation: utf8mb4_general_ci
  database: tanooki_development
  host: localhost
  username: root
  password: mypassword

test:
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4_general_ci
  collation: utf8mb4_general_ci
  database: tanooki_test
  host: 127.0.0.1
  username: root
  password: mypassword
  collation: utf8mb4_general_ci

production:
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4_general_ci
  collation: utf8mb4_general_ci
  database: tanooki_production
  host: dbaas-db-8389628-do-user-13712068-0.b.db.ondigitalocean.com
  username: deploy
  password: AVNS_v7h1tnVLVZ2X95by_oy
